name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "develop"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: greenticai/.github/.github/workflows/host-crate-ci.yml@main
    with:
      run-semver-checks: true
      semver-checks-package: serde_yaml_gtc
      checkout-submodules: "recursive"
      clippy-args: "--workspace --all-targets --all-features -- -A clippy::all"
      test-args: "--workspace --all-features"
